map('n', '<Tab>', '<Cmd> BufferLineCycleNext <CR>', create_desc 'Cycle [N]ext')
map('n', '<S-Tab>', '<Cmd> BufferLineCyclePrev <CR>', create_desc 'Cycle [P]revious')
map('n', '<leader>x', '<Cmd> BufferLinePickClose <CR>', create_desc 'Pick [C]lose')
map('n', '<A-S-z>', '<Cmd> BufferLineMovePrev <CR>', create_desc 'Move [P]revious')
map('n', '<A-S-c>', '<Cmd> BufferLineMoveNext <CR>', create_desc 'Move [N]ext')
map('n', '<leader>bp', '<Cmd> BufferLineTogglePin <CR>', create_desc 'Toggle [B]uffer [P]in')
