map('n', '<Tab>', '<Cmd> BufferLineCycleNext <CR>', create_desc 'Cycle [N]ext')
map('n', '<S-Tab>', '<Cmd> BufferLineCyclePrev <CR>', create_desc 'Cycle [P]revious')
map('n', '<leader>co', '<Cmd> BufferLineCloseOthers <CR>', create_desc 'Close [O]thers')
map('n', '<leader>z', '<Cmd> BufferLineCloseLeft <CR>', create_desc 'Close [O]thers')
map('n', '<leader>c', '<Cmd> BufferLineCloseRight <CR>', create_desc 'Close [O]thers')
map('n', '<A-S-j>', '<Cmd> BufferLineMovePrev <CR>', create_desc 'Move [P]revious')
map('n', '<A-S-k>', '<Cmd> BufferLineMoveNext <CR>', create_desc 'Move [N]ext')
map('n', '<leader>bp', '<Cmd> BufferLineTogglePin <CR>', create_desc 'Toggle [B]uffer [P]in')
