require 'custom.keymaps.generals'

require 'custom.keymaps.nvchad'

require 'custom.keymaps.nvimtree'
require 'custom.keymaps.tmux'
require 'custom.keymaps.move'
require 'custom.keymaps.lazygit'
require 'custom.keymaps.toggleterm'
require 'custom.keymaps.todo'
require 'custom.keymaps.competitive_programming'
require 'custom.keymaps.coderunner'
require 'custom.keymaps.copilot'
require 'custom.keymaps.undotree'
require 'custom.keymaps.markdown'
require 'custom.keymaps.flutter'
